language: php

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: PHPCS=1
    - php: 7.0
      env: SS4=1

before_script:
 - "if [ \"$PHPCS\" = \"1\" ]; then pyrus install pear/PHP_CodeSniffer; fi"
 - phpenv rehash
 - composer self-update || true
 - "if [ \"$SS4\" = \"1\" ]; then composer require 'silverstripe/framework:4.0.x-dev'; fi"
 - "if [ \"$SS4\" = \"1\" ]; then composer require 'silverstripe/config:1.0.x-dev'; fi"
 - composer install --prefer-dist

script:
 - vendor/bin/phpunit
 - "if [ \"$PHPCS\" = \"1\" ]; then phpcs --standard=PSR2 code/ bin/ tests/; fi"
